language: node_js
sudo: false
node_js:
- '10'
- '12'
- '14'
before_script:
- npm -v && node -v
after_script:
- npm run coverage
install:
- npm ci --no-optional
deploy:
  provider: npm
  email: vowstar@gmail.com
  api_key:
    secure: XvNLWwBnX8CyC9gYPHVvzifwqKmLJAMpi5a6t7cnO2wgzcfNuwIPNw3ou205tKE/2JpEt0Ptq6+wD8cY+vlgxwCRDdAAFPCNcANFK91OfyU3gbnTpczYuwzRwDRa+PXemwwdE8Y2+f3Uj3eBZu6Zxtn9bkIdHOWo11tp0Y3z+I0qM9EHQRp0WxOctK811PJmjJ76AUFs9UWzn9AZRWUsDXqb6oEVkvvtJ7uVPoWptAZfj0GOIVQ9/pjpAnw8ltn4wSWiK9d1pTYFm6ahCQd99X7194pFbw8oo1lTv5km9PsyiJfbQC1wjCXc5fEQVR6WJGT3ReCXdGZzi2Ta2zzGMKSyD/ZcjAYRBo36kPV+LqFpYEeg8aNUKbAZBTpV6cV6S7bCVHj9XBFVSlDNmjWPbBVsjC2xOwjZ869A4v8Wt1Q63ruHucjaDUuIEXoCnjlUYjhhiU6+AaCpLOFx3t1HxYRs0YAssJ1lwTBVbBLkTHX3pdouWSmoDYNrSun2sSLgzSq7AO2EXKwZqRzeuSZ2S6NRYNPS8Xh+bvSEe6oV5QiTT08owX+z/V9QK9s7V4jCoYSepJ1h/fny3K1M7twI6wgCq5AsVitk26VPdjQ0PfnpIP7+lyh3GdKgmlFsGcbIiHI2aEOmVfxeN4Z2Ijtl1skiu5mUyExGgsemW9s+BK0=
  on:
    tags: true
    repo: vowstar/honkit-tester
